---

- name: Ansible facts
  hosts: localhost
  connection: local
  tasks:
    - name: Ansible facts - read os-release - ID and VARIANT_ID
      ansible.builtin.shell: |
        . /etc/os-release
        printf '%s\n' "$ID" "$VARIANT_ID"
      register: os_release
      changed_when: false
      # ID: e.g.: bluefin, fedora
      # VARIANT_ID: e.g.: bluefin-dx, silverblue

    - name: Ansible facts - Set OS facts - ID and VARIANT_ID
      ansible.builtin.set_fact:
        os_id: "{{ os_release.stdout_lines[0] }}"
        os_variant_id: "{{ os_release.stdout_lines[1] }}"
