---

- name: Direnv config
  hosts: localhost
  connection: local
  tasks:
    - name: Direnv config - create config folder (env_user)
      tags: shellrc
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/direnv"
        state: directory
        owner: "{{ ansible_facts['env']['USER'] }}"
        group: "{{ ansible_facts['env']['USER'] }}"
        mode: "u=rwx,g=rx,o=rx"

    # - name: Direnv config - config (env_user)
    #   tags: shellrc
    #   ansible.builtin.blockinfile:
    #     path: "{{ ansible_facts['env']['HOME'] }}/.config/direnv/direnv.toml"
    #     create: true
    #     marker: "### {mark} 'direnv config' ANSIBLE MANAGED BLOCK ###"
    #     block: |
    #       [global]
    #       hide_env_diff = true
    #     owner: "{{ ansible_facts['env']['USER'] }}"
    #     group: "{{ ansible_facts['env']['USER'] }}"
    #     mode: u=rwx,g=rx,o=rx

    - name: Direnv config - project layouts - python - uv (env_user)
      tags: shellrc
      ansible.builtin.blockinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/direnv/direnvrc"
        create: true
        marker: "### {mark} 'direnv project layouts - python - uv' ANSIBLE MANAGED BLOCK ###"
        block: |
          layout_uv() {
              # for a (new) Python project-folder to be managed with uv
              # Alternativa solution: https://github.com/direnv/direnv/wiki/Python#uv

              if [[ ! -f "pyproject.toml" ]]; then
                  # if file 'pyproject.toml' does NOT! exist in current folder

                  log_status "File 'pyproject.toml' does NOT exist. Executing \`uv init\`."
                  uv init
              fi

              log_status "Updating the project's environment. Executing \`uv sync\`."
              uv sync # also creates/updates .venv + uv.lock, ...

              log_status "Activating virtual environment. Executing \`source .venv/bin/activate\`."
              source .venv/bin/activate
          }
        owner: "{{ ansible_facts['env']['USER'] }}"
        group: "{{ ansible_facts['env']['USER'] }}"
        mode: u=rwx,g=rx,o=rx
