---

- name: Nnn plugins
  hosts: localhost
  connection: local
  tasks:
    - name: Nnn plugins - download install script (env_user)
      tags: nnnplugs
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs
        dest: "/tmp/getplugs.sh"
        mode: "0777"

    - name: Nnn plugins - exec install script (env_user)
      tags: nnnplugs
      ansible.builtin.script: "/tmp/getplugs.sh"
