---

- name: User
  hosts: localhost
  connection: local
  tasks:
    # encrypted vault.yml contains initial 'user_password' for new user
    - name: Include vars - inventory - group_vars
      ansible.builtin.include_vars:
        dir: ../inventory/group_vars

    # 2nd user with sudo privileges in case of problems with 1st user
    - name: User - create new user account - R2D2
      become: true
      ansible.builtin.user:
        name: "R2D2"
        create_home: true
        shell: /bin/bash
        # groups: wheel,dialout,docker,incus-admin,libvirt,clamav
        groups: wheel
        append: true
        password: "{{ user_password | password_hash('sha512') }}" # "user_password" encrypted in ../inventory/group_vars/vault.yml

    # default "/etc/shadow": root:!::0:99999:7:::
    # - ! -> password locked; no login via password possible, only ssh-key or sudo allowed
    #
    # - name: User - block interactive login - root
    #   become: true
    #   ansible.builtin.user:
    #     name: "root"
    #     shell: /usr/sbin/nologin # blocks login with error message # or: "/bin/false": stops every login without error message
    #       # - prevents all interactive logins (incl. SSH, Console, su)
    #       # - advantage: keeps account for system services so they keep working
    #     # password_lock: true # locks / blocks login with password # already set by default, se "/etc/shadow"
    #       # - SSH-login with key still possible

    # maybe add: /etc/ssh/sshd_config: PermitRootLogin no

    # /usr/sbin/nologin + password_lock + PermitRootLogin no: no login via root at all, but accounts stays available for system things
    # -> you should not deactivate root user

    # ### CHECK

    - name: User - Check docker group
      ansible.builtin.getent:
        database: group
        key: docker
      register: docker_group
      changed_when: false
      failed_when: false  # Task wird nie als fehlgeschlagen markiert (bleibt "grün")
                          # echter Return-Code (z.B. 127 für "command not found", oder 1, ...) wird in "docker_check" gespeichert
      # ignore_errors: true # damit wäre die Ausgabe "rot", würde aber (einfach/ebenfalls) weiterlaufen

    - name: User - Check incus-admin group
      ansible.builtin.getent:
        database: group
        key: incus-admin
      register: incus_admin_group
      changed_when: false
      failed_when: false

    - name: User - Check libvirt group
      ansible.builtin.getent:
        database: group
        key: libvirt
      register: libvirt_group
      changed_when: false
      failed_when: false

    - name: User - Check clamav group
      ansible.builtin.getent:
        database: group
        key: clamav
      register: clamav_group
      changed_when: false
      failed_when: false

    # ### ADD to group(s)

    - name: User - Add R2D2 to docker group
      become: true
      ansible.builtin.user:
        name: "R2D2"
        groups: docker
        append: true
      when: "'docker' in docker_group.ansible_facts.getent_group"
      # when: docker_group.ansible_facts.getent_group.docker is defined

    - name: User - Add R2D2 to incus-admin group
      become: true
      ansible.builtin.user:
        name: "R2D2"
        groups: incus-admin
        append: true
      when: "'incus-admin' in incus_admin_group.ansible_facts.getent_group"

    - name: User - Add R2D2 to libvirt group
      become: true
      ansible.builtin.user:
        name: "R2D2"
        groups: libvirt
        append: true
      when: "'libvirt' in libvirt_group.ansible_facts.getent_group"

    - name: User - Add R2D2 to clamav group
      become: true
      ansible.builtin.user:
        name: "R2D2"
        groups: clamav
        append: true
      when: "'clamav' in clamav_group.ansible_facts.getent_group"
