---

- name: VS Code extensions config
  hosts: localhost
  connection: local
  tasks:
    - name: VS Code extensions config - Erstelle hilfsweise manuell 'Sync Settings' Extension Ordner für 'VS Code'
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/Code/User/globalStorage/zokugun.sync-settings"
        state: directory
        mode: "0775"

    - name: VS Code extensions config - Set/Copy 'Visual Studio Code' settings-file for Extension 'Sync Settings'
      ansible.builtin.copy:
        src: files/VSCode_Extension_Sync-Settings_settings.yml
        dest: "{{ ansible_facts['env']['HOME'] }}/.config/Code/User/globalStorage/zokugun.sync-settings/settings.yml"
        owner: "{{ ansible_facts['env']['USER'] }}"
        group: "{{ ansible_facts['env']['USER'] }}"
        mode: u=rw
